<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cloud.yunyat</groupId>
    <artifactId>javafx</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>javafx</name>
    <description>javafx</description>
    <modules>
        <module>model</module>
        <module>controller</module>
        <module>view</module>
        <module>app</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <java.version>21</java.version>
        <ini4j.version>0.5.4</ini4j.version>
        <javafx.platform>win</javafx.platform>
        <lombok.version>1.18.30</lombok.version>
        <netty-all.version>4.2.9.Final</netty-all.version>
        <log4j.version>2.25.3</log4j.version>
        <javafx.version>21.0.10-ea+1</javafx.version>
        
<!--        <javafx.controls.jar>${settings.localRepository}\org\openjfx\javafx-controls\${javafx.version}\javafx-controls-${javafx.version}-${javafx.platform}.jar</javafx.controls.jar>-->

<!--        <javafx.fxml.jar>${settings.localRepository}\org\openjfx\javafx-fxml\${javafx.version}\javafx-fxml-${javafx.version}-${javafx.platform}.jar</javafx.fxml.jar>-->
<!--        <javafx.graphics.jar>${settings.localRepository}\org\openjfx\javafx-graphics\${javafx.version}\javafx-graphics-${javafx.version}-${javafx.platform}.jar</javafx.graphics.jar>-->

<!--        <ini4j.jar>${settings.localRepository}\org\ini4j\ini4j\${ini4j.version}\ini4j-${ini4j.version}.jar</ini4j.jar>-->

<!--        <lombok.jar>${settings.localRepository}\org\projectlombok\lombok\${lombok.version}\lombok-${lombok.version}.jar</lombok.jar>-->

<!--        <io.netty.handler.jar>${settings.localRepository}\io\netty\netty-handler\${netty-all.version}\netty-handler-${netty-all.version}.jar</io.netty.handler.jar>-->
<!--        <io.netty.codec.base.jar>${settings.localRepository}\io\netty\netty-codec-base\${netty-all.version}\netty-codec-base-${netty-all.version}.jar</io.netty.codec.base.jar>-->
<!--        <io.netty.transport.jar>${settings.localRepository}\io\netty\netty-transport\${netty-all.version}\netty-transport-${netty-all.version}.jar</io.netty.transport.jar>-->
<!--        <io.netty.buffer.jar>${settings.localRepository}\io\netty\netty-buffer\${netty-all.version}\netty-buffer-${netty-all.version}.jar</io.netty.buffer.jar>-->
<!--        <io.netty.common.jar>${settings.localRepository}\io\netty\netty-common\${netty-all.version}\netty-common-${netty-all.version}.jar</io.netty.common.jar>-->
<!--        <netty.all.jar>${settings.localRepository}\io\netty\netty-all\${netty-all.version}\netty-all-${netty-all.version}.jar</netty.all.jar>-->
<!--        <log4j.api.jar>${settings.localRepository}\org\apache\logging\log4j\log4j-api\${log4j.version}\log4j-api-${log4j.version}.jar</log4j.api.jar>-->
<!--        <log4j.core.jar>${settings.localRepository}\org\apache\logging\log4j\log4j-core\${log4j.version}\log4j-core-${log4j.version}.jar</log4j.core.jar>-->

<!--        <cloud.yunyat.model.master>\model-master\target\classes\</cloud.yunyat.model.master>-->

<!--        <module.path>${javafx.controls.jar}${path.separator}${javafx.fxml.jar}${path.separator}${javafx.graphics.jar}${path.separator}${ini4j.jar}${path.separator}${lombok.jar}${path.separator}${io.netty.handler.jar}${path.separator}${io.netty.codec.base.jar}${path.separator}${io.netty.transport.jar}${path.separator}${io.netty.buffer.jar}${path.separator}${io.netty.common.jar}${path.separator}${log4j.core.jar}${path.separator}${log4j.api.jar}</module.path>-->
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- 公共依赖版本 -->
            <dependency>
                <groupId>org.ini4j</groupId>
                <artifactId>ini4j</artifactId>
                <version>${ini4j.version}</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.13.2</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${log4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>${log4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty-all.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-codec-base</artifactId>
                <version>${netty-all.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>5.4.0</version>
                <exclusions>
                    <!-- 排除 commons-lang3-->
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-lang3</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.18.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- 统一 maven-compiler-plugin 配置 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.0</version>
                    <configuration>
<!--                        <fork>true</fork>-->
                        <release>${java.version}</release>
<!--                        <useIncrementalCompilation>false</useIncrementalCompilation>-->
                        <annotationProcessorPaths>
                            <!-- lombok 作为编译注解处理器（如果需要） -->
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
<!--                        <compilerArgs combine.children="append">-->
<!--                            <arg>&#45;&#45;add-modules</arg>-->
<!--                            <arg>javafx.controls,javafx.fxml,javafx.graphics,ini4j,lombok,io.netty.handler,io.netty.codec,io.netty.transport,io.netty.buffer,io.netty.common,org.apache.logging.log4j.core,org.apache.logging.log4j,cloud.yunyat.model.master</arg>-->
<!--                            <arg>&#45;&#45;module-path</arg>-->
<!--                            &lt;!&ndash;suppress UnresolvedMavenProperty &ndash;&gt;-->
<!--                            <arg>${module.path}${path.separator}${session.executionRootDirectory}${cloud.yunyat.model.master}</arg>-->
<!--                        </compilerArgs>-->
                    </configuration>
                </plugin>
                <!-- 如果用 JavaFX，可在这里添加 javafx-maven-plugin 配置（可选） -->
<!--                <plugin>-->
<!--                    <groupId>org.openjfx</groupId>-->
<!--                    <artifactId>javafx-maven-plugin</artifactId>-->
<!--                    <version>0.0.8</version>-->
<!--                    <configuration>-->
<!--                        <mainClass>cloud.yunyat.app.MainApp</mainClass>-->
<!--                    </configuration>-->
<!--                </plugin>-->
            </plugins>
        </pluginManagement>
    </build>
</project>